### ISSUE TITLE
When sending an email, is is the data param an dictionary string,object instead of just an object

### ISSUE THREAD

**Issue by markalanevans** [sendwithus/sendwithus_csharp#13]
I was just wondering why your design for sending an email has the 2nd param being an dict<string,object> instead of just passing in an object.

Wouldn't it have been easier for all of us to just pass in an object? I'd imagine most of us are creating domain objects for each email, and then are now forced to convert it to a dictionary, or being forced to namespacing the data one level deep in the dictionary.

Since you are just serializing the object into json , and without knowing your reasons, i'd suggest create a constructor overload which accepts an object rather than a dictionary. 

Thoughts?

**Comment by demoore** [comment]
I'm not privy to the original design decision — @chennig might be able to chime in) — but I would happily accept a PR if you want to extend the client to support this.

**Comment by chennig** [comment]
@markalanevans I went with the <string, object> format for the template data because that's the format that the API expects to receive the data in.  But as you said, that's also exactly the json output that you'd get from serializing an object.  Given that you're probably representing the template data in specific, custom classes instead of a dictionary, I can see how having to map those objects to a dictionary would be awkward.  Your suggestion of overloading the call with a second constructor that accepts an object instead of a dictionary sounds good to me.
